title: "0xWalid | Offensive Security Specialist"
email: contact@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Digital Dossier of a Junior Penetration Tester & Security Researcher.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  0xWalid
linkedin_username: thewaleedahmed

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Custom Variables
google_fonts:
  - "Space+Grotesk:wght@300;400;500;600;700"
  - "JetBrains+Mono:wght@400;700"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
